### ISSUE TITLE
Add British Library Subject Headings?

### ISSUE THREAD

**Issue by nichtich** [gbv/bartoc.org#118]
"British Library Subject Headings" is indexed in K10plus but what exactly is this vocabulary? There was PRECIS (1974–
1990) and COMPASS (1991–1996) at least

**Comment by jeanninebeeken** [comment]
Hi, information about K10plus can be found here https://www.bszgbv.de/services/k10plus/ 
Examples of UKMARC as used by BL etc. (PRECIS/COMPASS) are here https://www.bl.uk/bibliographic/ukmarcmanual/ukmarc_tags600.pdf or https://eprints.soton.ac.uk/161713/1/SWRLIN_MaRC_Manual_2001.pdf 
BARTOC already contains a link to http://bartoc.org/en/node/17850#access (BL Terms RDF Schema), and to http://bartoc.org/en/node/17850#access (LOV).

**Comment by nichtich** [comment]
Thanks!
