### ISSUE TITLE
Show topic labels for DDC, EuroVoc and ILC

### ISSUE THREAD

**Issue by nichtich** [gbv/bartoc.org#12]
By now topics (DDC and EuroVoc) are only shown with their URI. For client-side rendering we might use cocoda-sdk (when https://github.com/gbv/cocoda-sdk/issues/15 has been implemented). For more reliable access we should import DDC, EuroVoc and ILC into the bartoc jskos-server instance.

**Comment by nichtich** [comment]
Even better would be #16 to browse in the vocabularies.

**Comment by stefandesu** [comment]
This is implemented in dev, right?
