### ISSUE TITLE
Check and add vocabularies from the recent survey

### ISSUE THREAD

**Issue by UmaB7** [gbv/bartoc.org#131]
A survey on local subject indexing and form information contained in this local subject indexing data, conducted by the VZG.

Target Group: GBV/SWB libraries.

"In order to improve the search options for Lukida (discovery system), it is planned to set up a new (search) facet based on field 1131 (type of content). One consideration here is to raise any existing form information or coding of subject indexing at local level to the bibliographic level." -Survey Introduction

**Comment by DavidBRohrer** [comment]
[Auswertung der Umfrage.pptx](https://github.com/gbv/bartoc.org/files/7897705/Auswertung.der.Umfrage.pptx)
This is the survey. 
I added the "Mathematics Subject Classification System". Seems to be a popular classification in mathematics.

**Comment by DavidBRohrer** [comment]
added some more.

**Comment by DavidBRohrer** [comment]
"some" means: Systematik der herzoglichen Sammlung, Systematik der Bibliographia Cartographica
