### ISSUE TITLE
Delete specific BARTOC entry

### ISSUE THREAD

**Issue by DavidBRohrer** [gbv/bartoc.org#166]
With the following search (https://bartoc.org/vocabularies?search=vorpommern) two entries of the same vocabulary are found. https://bartoc.org/en/node/1986 is the correct one and should be left. 
https://bartoc.org/en/node/20398 is one entry too much and should be deleted.

Problem: at the moment, when deleting an entry, adding new entries works no more. This should be fixed before. 

Further entries to delete;

- https://bartoc.org/en/node/18706 (https://bartoc.org/en/node/20303 is the right one)
- https://bartoc.org/en/node/20329 (https://bartoc.org/en/node/20000 is the right one)

**Comment by nichtich** [comment]
Deleting vocabularies breaks creation of new vocabularies. Requires https://github.com/gbv/jskos-server/issues/161.

**Comment by DavidBRohrer** [comment]
see also #155

**Comment by stefandesu** [comment]
I adjusted the code for minting a new URI with the new feature in https://github.com/gbv/jskos-server/issues/161. Deleting entries should now be possible without causing issues.

Note that when deleting the very latest record (i.e. currently highest ID), its URI will be reused for the next created record. Is that an issue @nichtich? If yes, we would need to save a counter somewhere...

**Comment by nichtich** [comment]
Reuse of last record is fine.

**Comment by stefandesu** [comment]
> Further entries to delete;
> 
>     * [bartoc.org/en/node/18706](https://bartoc.org/en/node/18706) ([bartoc.org/en/node/20303](https://bartoc.org/en/node/20303) is the right one)
> 
>     * [bartoc.org/en/node/20329](https://bartoc.org/en/node/20329) ([bartoc.org/en/node/20000](https://bartoc.org/en/node/20000) is the right one)

I just looked at these entries and they haven't been unified yet. Furthermore, I am personally not confident that these are really duplicates, especially in the second case. @nichtich Can you take a look?



> [bartoc.org/en/node/20398](https://bartoc.org/en/node/20398) is one entry too much and should be deleted.

I have deleted http://bartoc.org/en/node/20398.

**Comment by nichtich** [comment]
- https://bartoc.org/en/node/18706 can be deleted
- https://bartoc.org/en/node/20329 can be deleted

**Comment by stefandesu** [comment]
Done.
