### ISSUE TITLE
Correct Metadata of registries

### ISSUE THREAD

**Issue by DavidBRohrer** [gbv/bartoc.org#175]
Collection of wrong metadata of registries:

* https://bartoc.org/en/node/1917: Homepage has changed to https://www.dgiwg.org/resources.
* https://bartoc.org/en/node/1921: Homepage is beeing rebuilt at the time

**Comment by nichtich** [comment]
https://bartoc.org/en/node/1724: Moved to https://vocab.nerc.ac.uk/ and supports multiple APIs

**Comment by nichtich** [comment]
I kept <https://bartoc.org/en/node/1921> as the page may be back in the future.
