### ISSUE TITLE
Add an entry for the Bioregistry

### ISSUE THREAD

**Issue by cthoyt** [gbv/bartoc.org#197]
The Bioregistry is a registry of life and natural sciences ontologies/databases/controlled vocabularies that mint their own identifier spaces. It contains metadata like the name, description, homepage, etc. for humans. It contains prefix and URI expansion information for semantic web usage. It also harmonizes and aligns other registries with (partially) overlapping focus (including BARTOC!).

If you're familiar with Identifiers.org or Name-to-Thing (N2T), the Bioregistry is a logical successor that is fully curated in the open with public code and data. I am the contact person for the Bioregisry and can answer any questions.

| Artifact | Link |
|-------|-------|
| Website | https://bioregistry.io | 
| Code | https://github.com/biopragmatics/bioregistry |
| Publication | [Unifying the identification of biomedical entities with the Bioregistry](https://doi.org/10.1038/s41597-022-01807-3) |
| FAIRsharing page about the Bioregistry | https://fairsharing.org/FAIRsharing.250a8c |
| Bioregistry page about the Bioregistry  | https://bioregistry.io/registry/bioregistry |
| Bioregistry page about BARTOC | https://bioregistry.io/registry/bartoc |

**Comment by nichtich** [comment]
Thanks, I'll have a closer lookl at Bioregistry!
