### ISSUE TITLE
Abbreviation field is inconsistent in some places

### ISSUE THREAD

**Issue by cthoyt** [gbv/bartoc.org#200]
When aligning the Bioregistry with content in BARTOC, I get the following three instances where a space is inside the abbreviation field:

[bartoc:20058] space in abbr.: Hist Ant
[bartoc:20292] space in abbr.: ICOM, ICOFOM
[bartoc:474] space in abbr.: MSC, MSC2010

Are the oversights? It's not clear if it should be possible to have multiple abbreviations, and if so, if they should be delimited in free text or if the field should be a list instead of a string.

I'm not sure what to do about Hist Ant. Maybe this one doesn't belong at all in this record

**Comment by nichtich** [comment]
Thanks! I've fixed ICOM and MSC as there should only be one abbreviation (mapped to `skos:notation`) per vocabulary. Spaces are not forbidded at least up to now.

**Comment by cthoyt** [comment]
Danke @nichtich :)
