### ISSUE TITLE
Add voc4cat to bartoc?

### ISSUE THREAD

**Issue by dalito** [gbv/bartoc.org#210]
Hi, in NFDI4Cat we have been developing [voc4cat](https://w3id.org/nfdi4cat/voc4cat/dev) as a vocabulary for catalysis and related disciplines. It has been slowly gaining more users. Could we add it to BARTOC? - For us it would also be of interest to see how compliant we are with [SKOSMOS](https://skosmos.bartoc.org/) (cc  @nmoust).

URL: https://github.com/nfdi4cat/voc4cat

**Comment by nichtich** [comment]
Thanks! We added https://bartoc.org/en/node/20501 - please let us know is something is missing. To check SKOS compliance have a look at https://github.com/skohub-io/shapes - we don't offer a validation service yet. The hosting service https://skosmos.bartoc.org/ is work in progress as well, but we'll get back to it this year.

**Comment by dalito** [comment]
Thank you, Jakob!
