### ISSUE TITLE
Enable login if run under different domain

### ISSUE THREAD

**Issue by nichtich** [gbv/bartoc.org#31]
The application will be hostet at https://bartoc.org/ but the login server is at https://coli-conc.gbv.de/login/ so it won't work when third party-cookies are disabled (should be the default on modern browsers). Possible solutions?

See also https://github.com/gbv/login-client/issues/10 (documentation) and https://github.com/gbv/login-server/issues/9 (previous discussion)

**Comment by stefandesu** [comment]
There has to be a solution, but I'm having a hard time understanding how it all works. Here are two relevant SO threads I found:

- https://stackoverflow.com/questions/16186645/cross-domain-cookies-a-maybe-new-idea
- https://stackoverflow.com/questions/46288437/set-cookies-for-cross-origin-requests

**Comment by nichtich** [comment]
Login does work but not with Safari browser.
