### ISSUE TITLE
vocabulary search for does not show ILC

### ISSUE THREAD

**Issue by nichtich** [gbv/bartoc.org#48]
See http://bartoc.org/vocabularies?subject=https%3A//bartoc.org/ILC/1/V-general-class: the subject is used for filtering but the filter is not shown in the subject editor to filter by ILC class.

**Comment by stefandesu** [comment]
Easy issue: The ILC that was provided in `indexingSchemes` had a http namespace, while the concepts actually use https. I used the namespace from https://bartoc.org/en/node/472 instead.
