### ISSUE TITLE
Sort list of vocabularies

### ISSUE THREAD

**Issue by nichtich** [gbv/bartoc.org#55]
See https://github.com/gbv/jskos-server/issues/118

**Comment by nichtich** [comment]
The search page should show the current search criteria and allow to change it. For `sort=modified` and `sort=created` the newest schemes should come first.

**Comment by stefandesu** [comment]
There's one issue: Currently, search and filter and *completely* separate. Search uses the `/voc-search` endpoint while filter uses `/voc`. With the latter, we can filter and sort, but the search results will always be sorted by relevance. There's currently no way in jskos-server to use filtering and sorting in searches.

What should we do here? It would be easy to add sorting to the filter, but ideally, the filter and search would work together which would need big changes in jskos-server.

**Comment by nichtich** [comment]
We should better split search (by relevance) and browse (filtering) in two tabs. Sorting can be enabled in the latter only.

**Comment by stefandesu** [comment]
I split search and filter into tabs:

https://user-images.githubusercontent.com/3275148/105840042-a91db780-5fd2-11eb-8336-5377b610f380.mp4

If that looks good to you, I would commit it and then add the sorting.

**Comment by stefandesu** [comment]
I just noticed that sorting for schemes does not have a sort order parameter, so sorting is always ascending. Also, the `modified` field does not exist for all schemes (well, there are only two or three in the whole database where the field doesn't exist) which messes with the sorting. So this still requires changes in jskos-server before it makes sense to implement it here.

**Comment by stefandesu** [comment]
https://github.com/gbv/jskos-server/releases/tag/v1.2.2 is now out and it works as expected now. 👍 Only needs to be merged.

**Comment by stefandesu** [comment]
(Very smart of me to close the issue before pushing the actual commit, oops.)

**Comment by stefandesu** [comment]
I improved the sorting options and layout in 93c00d6ab08bd4eaa444dbe0a33e4cafae95a0fb and 467085d1aacb92e3078db4f586ebe591bb6c2a7e (mistakenly used the wrong issue number 🙈).
