### ISSUE TITLE
Vocab edition

### ISSUE THREAD

**Issue by gatemezing** [gbv/bartoc.org#57]
Have a way to retrieve automatically some properties based on the URI of the vocab to add.
This will reduce the time to manually add those fields by a human.

**Comment by nichtich** [comment]
There is an API at http://bartoc.gbv.de/api/ (please switch to http://bartoc.org/api/ this week), e.g. get all information about DDC:

http://bartoc.gbv.de/api/data?uri=http%3A%2F%2Fbartoc.org%2Fen%2Fnode%2F241&properties=*

It's also possible to modify records via this API but this needs better documentation - is this your use case or just retrieval?
