### ISSUE TITLE
Add canonical links to bartoc.org

### ISSUE THREAD

**Issue by nichtich** [gbv/bartoc.org#60]
See https://en.wikipedia.org/wiki/Canonical_link_element to indicate canonical URI of a record.

**Comment by stefandesu** [comment]
Please check the commit for this unbelievably complicated implementation. 😁

Questions:
1. Can we assume that the `uri` field always refers to the canonical URI, or do we need any checks?
2. The way it's implemented now, it is added for all items, so vocabularies, concepts, and registries. Is that okay?
3. It is also added to the `/edit` page, is that a problem? (In fact, it will be added to any page where `item` is available in the template.)
