### ISSUE TITLE
Enable automatic upgrade to HTTPS for bartoc.org

### ISSUE THREAD

**Issue by stefandesu** [gbv/bartoc.org#68]

**Comment by nichtich** [comment]
Unfortunately the BARTOC URIs are http URIs. Still https can be used but just copy & paste a BARTOC URL would not work anymore for unique identification.

**Comment by nichtich** [comment]
The subdomain www.bartoc.org also needs to be redirected.

**Comment by stefandesu** [comment]
> Unfortunately the BARTOC URIs are http URIs. Still https can be used but just copy & paste a BARTOC URL would not work anymore for unique identification.

I think the URI and the web address can be different as long as the URI forwards to the web address. The URI field should still show the http URI.

Also, newly added vocabularies could be assigned a https URI.

**Comment by nichtich** [comment]
Ok, but this is better implemented in the HTTP proxy, no?

> Also, newly added vocabularies could be assigned a https URI.

Too much confusion, better all BARTOC URIs have same protocol

**Comment by nichtich** [comment]
Requires #60

**Comment by stefandesu** [comment]
> Ok, but this is better implemented in the HTTP proxy, no?

Yeah, this wasn't an issue about changing anything about BARTOC per se, rather about how bartoc.org is hosted. Our other services have automatic HTTPS upgrade, so we could enable it for BARTOC as well. (However, right now I'm not sure whether this is done on our servers or on the VZG web proxy. Probably the latter.)

**Comment by VladimirAlexiev** [comment]
@nichtich the current state:
- http://bartoc.org/ works perfectly but the browser bar says "not secure"
- http://www.bartoc.org/ redirects to http://bartoc.org/ (great!)
- https://bartoc.org/ works perfectly
- https://www.bartoc.org/ complains loudly "not secure" and says "You are here: https://www.gbv.de/" and serves only parts of the page
  - Please fix that to redirect to https://bartoc.org/ 
- https://www.bartoc.org/en/node/1036 says "This page does not seem to exist…"
  -  Please fix that to redirect to https://bartoc.org/en/node/1036 

Thanks!

**Comment by stefandesu** [comment]
@VladimirAlexiev Thanks for the investigation, we should absolutely fix that! Do you think HTTP should automatically be upgraded to HTTPS in all cases? I would personally prefer not to use any site in HTTP anymore, but @nichtich seems to disagree.

**Comment by VladimirAlexiev** [comment]
I've never been bit by http, but browsers actively discourage the use if such sites, so...

**Comment by nichtich** [comment]
- [x] https://bartoc.org/ works perfectly
- [x] http://bartoc.org/ redirects to https://bartoc.org/
- [ ] http://www.bartoc.org/ redirects to https://bartoc.org/
- [ ] https://www.bartoc.org/en/node/1036 redirects to https://bartoc.org/en/node/1036

**Comment by VladimirAlexiev** [comment]
Hi @nichtich, @stefandesu !

Could you also fix https://bartoc-skosmos.unibas.ch/en/:
- if you click on the logo, that's http://bartoc-skosmos.unibas.ch/en/ (http not https)
- which redirects to https://bartoc-skosmos.unibas.chen/, but notice the slash before `en` has been mangled
- which of course is a non-existing domain

**Comment by stefandesu** [comment]
Hi @VladimirAlexiev!

While the logo does link to the HTTP site, the redirect works fine for me. But anyway, I'm actually not sure who is responsible for BARTOC Skosmos as it is separate from BARTOC itself. Maybe @nichtich knows more.

**Comment by nichtich** [comment]
Anything related to bartoc-skosmos.unibas.ch requires #186
