### ISSUE TITLE
Align APIs with BARTOC FAST

### ISSUE THREAD

**Issue by nichtich** [gbv/bartoc.org#93]
Check whether all vocabularies listed via their APIs at https://bartoc-fast.ub.unibas.ch/bartocfast/about are included in BARTOC with API field.

**Comment by schuchaa** [comment]
51.15.194.251 - link does not work, name not findable in Vocabularies
data.ub.uio.no - not findable in Vocabularies
FORTH = Backbone Thesaurus (BBT)? - not findable in Vocabularies
HTW-Chur - link does not work, name not findable in Vocabularies
Irstea - "The thesaurus formerly used at Irstea to index publications and datasets. This vocabulary is no longer maintained. A large part of the concepts is included in the INRAE’s thesaurus." - not findable in Vocabularies
Legilux - name not findable in Vocabularies
lobid-gnd - API does not work 
Loterre -  name not findable in Vocabularies
LuSTRE -  name not findable in Vocabularies
MIMO - API does not work 
OZCAR-Theia - link does not work, name not findable in Vocabularies
Research-Vocabularies-Australia - 
ScoLOMFR - name not findable in Vocabularies
UAAV -name not findable in Vocabularies
